### ISSUE TITLE
calibration: 2 pixels at boresight,  2 years simulation band 9 90 GHz

### ISSUE THREAD

**Issue by zonca** [zonca/pico-simulations#15]
2 pixels, 4 detectors at: 0, 45°, 90, e 135°
All boresight pointing.

@ziotom78 still 2 years? With the same configuration of https://github.com/zonca/pico-simulations/issues/11?

**Comment by ziotom78** [comment]
@zonca Yep.

**Comment by zonca** [comment]
see https://github.com/zonca/pico-simulations/pull/23
