### ISSUE TITLE
Results of 1 pixel boresight pointing, 2 years, band 9 90 GHz, no foregrounds

### ISSUE THREAD

**Issue by zonca** [zonca/pico-simulations#16]
For calibration tests, reran the configuration in #11 with only CMB + Solar Dipole + Noise, results available in:

    /global/cscratch1/sd/zonca/pico/cal_sims/201804_boresight_1pix_2years_nofg

**Comment by zonca** [comment]
maps look reasonable 

![download 8](https://user-images.githubusercontent.com/383090/39665191-6889fb60-5090-11e8-9d62-0bbae15ee131.png)
![download 7](https://user-images.githubusercontent.com/383090/39665192-68b12bf4-5090-11e8-8022-60d092cabfd1.png)
![download 6](https://user-images.githubusercontent.com/383090/39665193-68cd4a8c-5090-11e8-9c19-d902543811eb.png)
![download 5](https://user-images.githubusercontent.com/383090/39665194-68e62b4c-5090-11e8-9af0-5926e00be9f6.png)

**Comment by ziotom78** [comment]
Ok, I ran the calibration code, results seem reasonable. There is a 0.04% bias in the gains which might be due to the fact that TOAST includes the quadrupolar correction in the simulation of the dipole signal, but apart from that everything looks ok.

**Comment by zonca** [comment]
very good, I'll tag all the software and archive the results, feel free to make edit https://github.com/zonca/pico-simulations/tree/master/calibration_sim/runs/201804_boresight_1pix_2years/README.md with reference to your results and/or software
