### ISSUE TITLE
Test PICO band 9 sparse sampling

### ISSUE THREAD

**Issue by zonca** [zonca/pico-simulations#18]
Reduce sampling with:
* half sampling rate 126->63
* less detectors per wafer 19->3, so total detectors 684->108
Reduction is a factor of 12.6666

ran 30 days on 30 nodes

see comparison of hitmaps:
https://gist.github.com/zonca/d9f462502f51c3085604708204a513de

@tskisner @keskitalo, let's take a look at this at the call

**Comment by tskisner** [comment]
Very interesting...  Thanks for making this test!

**Comment by zonca** [comment]
@jdborrill the run took 6.6 min on 30 nodes

**Comment by zonca** [comment]
@jdborrill @tskisner @keskitalo, here are the 3 focalplanes, definitely I shouldn't have used 3...running now with 7.

Full band:
![pico_09](https://user-images.githubusercontent.com/383090/40300529-c0e4735c-5ce9-11e8-84e8-6a7975837e20.png)

Sparse, 3 pixels per wafer, 108 detectors total:
![pico_09_108det](https://user-images.githubusercontent.com/383090/40300528-c0b3f36c-5ce9-11e8-9b4b-6747dae68a9f.png)

Sparse, 7 pixels per wafer, 252 detectors total:
![pico_09_252det](https://user-images.githubusercontent.com/383090/40300527-c073d6ce-5ce9-11e8-9575-e98f46713fc8.png)

**Comment by zonca** [comment]
Ratio of the sparse hitmap (after scaling it up to same total number of samples) to the full hitmap for the bad focalplane of 108 detectors:

![download 10](https://user-images.githubusercontent.com/383090/40301121-660f1b7e-5ceb-11e8-924a-3c19e15ce939.png)

**Comment by keskitalo** [comment]
I am confused by the last post. You say "for the bad focalplane" but the title of the plot says "corrected sparse". Should I read this as being essentially the result from last week? Are you still running the simulation with the corrected focalplane?

**Comment by zonca** [comment]
yes, I posted last week's result for comparison, the new one is still in the queue

**Comment by zonca** [comment]
ok, here is with 252 detectors, it is a lot better:

![hitmap_ratio_252](https://user-images.githubusercontent.com/383090/40318563-48e9587c-5d25-11e8-9395-fb14ecf6844d.png)

It ran in 3:20min on 60 nodes (still 30 days). Now the scale factor is 5.4.
I'll submit a 1 year run.
