### ISSUE TITLE
Full focal plane noise simulation band 9 1 year sparse

### ISSUE THREAD

**Issue by zonca** [zonca/pico-simulations#19]
* band 9
* less detectors: 252 detectors instead of 684, 7 per wafer, see focalplane plot in https://github.com/zonca/pico-simulations/issues/18
* half sampling rate
* multiplied the NET by `sqrt(252/684)` to get back a noise covariance map and noise map equal to the full focal plane, will scale up the hitmap by `684/252*2~5.4`
* using the code in https://github.com/zonca/pico-simulations/pull/9

**Comment by zonca** [comment]
it ran successfully in 6:20 min!

**Comment by zonca** [comment]
@tskisner @keskitalo @jdborrill

The maps look reasonable:

![band9_sparse_1year_hitmap](https://user-images.githubusercontent.com/383090/40533126-069e9632-6002-11e8-9256-a615395362eb.png)
![band9_sparse_1year_i](https://user-images.githubusercontent.com/383090/40532869-29d95368-6001-11e8-94bb-20fb0c212be5.png)
![band9_sparse_1year_q](https://user-images.githubusercontent.com/383090/40532868-29bdb1f8-6001-11e8-9415-8736b0fdefbd.png)
![band9_sparse_1year_u](https://user-images.githubusercontent.com/383090/40532867-295f1030-6001-11e8-98ff-e1c4b3e1dc52.png)

I already created a corrected version of the hitmap

maps are in:

`/global/cscratch1/sd/zonca/pico/full_focal_plane_noise/band_09_sparse_252_scalednoise_1year/out_000`

any tests it would be useful to run on those maps?

@jdborrill should I copy them to an official location? I was thinking about adding a README that just points to a github page I'll create with details about the sim, is it ok? (like this one I made for Maurizio's run: https://github.com/zonca/pico-simulations/tree/master/calibration_sim/runs/201804_boresight_1pix_2years)

**Comment by zonca** [comment]
submitted band 10 with scaled noise, 7 pix per wafer, 63 Hz sampling

**Comment by jdborrill** [comment]
Once they're completed and validated, we should put the maps and the README
in the PICO project space and put a post on the PICO wiki.

J

**Comment by zonca** [comment]
@tskisner @keskitalo

ok, I have got results for band 10 as well, I was working on validation, I have an issue with noise spectra.
I don't see the white noise plateau:

![band_10_tt_lin](https://user-images.githubusercontent.com/383090/40690264-8687edec-63a6-11e8-8960-3b0b50cd400f.png)
![band_10_tt_log](https://user-images.githubusercontent.com/383090/40690265-86a47d68-63a6-11e8-9faf-e72d2cc68899.png)

It has been a long time since I did this, can you crosscheck my notebook? https://gist.github.com/zonca/1e8f746c1addc5162f0a814d48e4a499

Is it possible any of the 1/f noise parameters is wrong? see table here: https://github.com/hpc4cmb/toast-pico/blob/master/params/bands.txt

**Comment by keskitalo** [comment]
@zonca looks like bands.txt lists the knee frequencies in mHz. I believe the focalplane pickle file is expected to be in Hz. Having a very high knee frequency would certainly explain the lack of noise plateau in your maps. The units also apply to the minimum frequency.

**Comment by zonca** [comment]
thanks! I fixed it and relaunched the job

**Comment by zonca** [comment]
now results look fine, see my validation here:

https://gist.github.com/zonca/0ccf6bf5b93669ce426262ff549ce8a3

I'll go ahead and submit all the jobs, if you have suggestion for other checks I can add to the validation please let me know!

**Comment by zonca** [comment]
ok, I'll open a new issue for the full run results
