### ISSUE TITLE
Completed sparse focal plane noise simulations for all bands, 1 year

### ISSUE THREAD

**Issue by zonca** [zonca/pico-simulations#20]
* Ran all bands with 7 pixels / wafer and 63 Hz sampling (unless sampling was already below 63 Hz)
* I ran my validation code and checked all the II spectra and they agree with the noise covariance matrix.
* I created the corrected hitmaps

maps are available in:

    /global/cscratch1/sd/zonca/pico/full_focal_plane_noise/band_??_sparse_scalednoise_1year/

@jdborrill should I create a folder under `/project/projectdirs/pico`? what folder name and what naming convention for the files?

**Comment by jdborrill** [comment]
It would be useful to compare the noise maps/angular power spectra with the
same runs with a higher pixel/wafer and/or sampling rate, just to get a
feel for how much we're losing in the approximation.

Meanwhile these should be copied to the PICO project directory -

/project/projectdirs/pico/noise/

and then lets keep maps with a particular degree of approximation together,
subdirectory by subdirectory, and use the usual file naming conventions.

 J

**Comment by zonca** [comment]
thanks @jdborrill I am trying to run band 9 with the full focalplane but still half sampling rate and for 6 months. So I can compare this full focal plane with the sparse focal plane.

**Comment by zonca** [comment]
@jdborrill can you please point me to a folder with maps in the usual file naming convention?

**Comment by zonca** [comment]
released, see README https://github.com/zonca/pico-simulations/tree/master/full_focal_plane/runs/201806_sparse_focal_plane_noise

**Comment by zonca** [comment]
@jdborrill @keskitalo
I ran a 30 days band 9 map both for the complete and the sparse focalplanes, I removed all pixels with less than 1 minute of integration time, the output maps T spectra agree:

![30days_noise_comparison](https://user-images.githubusercontent.com/383090/41649237-629ac1ee-747b-11e8-9e82-95b3969ef620.png)

I checked the dipole in map domain, the sparse map has 14e-3 muK, while the full focalplane map as 7e-3 muK. I checked also the 1 year simulation and that has 6e-3 muK.

**Comment by keskitalo** [comment]
Excellent!

-R

**Comment by jdborrill** [comment]
What is in these maps? Is the dipole variation within the expected range?

Julian

**Comment by zonca** [comment]
@jdborrill I think so, they are really tiny, ~1% of a microK

**Comment by zonca** [comment]
published to wiki: https://zzz.physics.umn.edu/ipsig/20180629_full_focal_plane_noise_sims
