### ISSUE TITLE
Apply calibration to TOAST timelines

### ISSUE THREAD

**Issue by zonca** [zonca/pico-simulations#21]
Get an input FITS file in a predefined format and apply gain to TOAST timelines on the fly

there is a suitable function in toast: https://github.com/hpc4cmb/toast/blob/df23d92042d38f2c280234f0aeb5546272ead93e/src/python/tod/tod_math.py#L19

but it is currently not used in any of the pipelines, need to add support for it

**Comment by ziotom78** [comment]
I have copied the source code of the script that produces FITS files containing gains on Edison. It's in `/global/cscratch1/sd/zonca/pico/cal_sims/gain2toast.py`. In the same folder there is also an example, `test_gains.fits`, which contains the gains computed for two detectors `0A` and `0B`.

**Comment by zonca** [comment]
Implemented in https://github.com/hpc4cmb/toast/pull/250

**Comment by zonca** [comment]
already used to run the gain simulation in https://github.com/zonca/pico-simulations/pull/23

**Comment by zonca** [comment]
@ziotom78 I am still debugging issues in the pipeline,
in the meantime would you implement the new format suggested by Ted at https://github.com/hpc4cmb/toast/pull/250 in your `gain2toast.py` script and generate again the gains for the simulation in this new format?

**Comment by zonca** [comment]
ok, I finalized this in #250, I also added a utility function useful to write calibration files from a dictionary
