### ISSUE TITLE
New PICO focalplane for full focal plane simulations

### ISSUE THREAD

**Issue by zonca** [zonca/pico-simulations#3]
@tskisner @jdborrill, are the new features of the focalplane generation for PICO finalized?
Can you generate the focalplane for the noise sims (or explain me how to generate it)?

**Comment by tskisner** [comment]
Hi @zonca, work in progress, should be done in about a day.

**Comment by zonca** [comment]
https://github.com/hpc4cmb/toast-pico

```
$>  toast_pico_hardware.py --bands params/bands.txt --pixels
params/pixels.txt --fov 12.15 --plot
```

which will dump 2 different testing formats (yaml and json, am
investigating hdf5 now) and make some pretty plots.  To dump pickle
files compatible with the toast example scripts, use a different tool:

```
$>  toast_pico_pkl.py --bands params/bands.txt --pixels
params/pixels.txt --fov 12.15
```

**Comment by tskisner** [comment]
Thanks for posting it in a better place.  I still need to apply the 30 degree rotation of the whole focalplane (so that it is correct for the scan direction) but that is a detail for now.

**Comment by zonca** [comment]
@tskisner is the 30 deg rotation done?

**Comment by tskisner** [comment]
Sorry for the delay, just pushed that change to toast-pico so that the detectors are in a line along the scan direction (or should be).  If you do a few-second sim and see the detector hits not trailing each other, then just change that overall rotation angle:
https://github.com/hpc4cmb/toast-pico/blob/master/toast_pico/hardware.py#L145

**Comment by zonca** [comment]
@tskisner here is 3.8 sec of band 9, how do I tell?

![pico_4sec_hitmap](https://user-images.githubusercontent.com/383090/36487056-46a66bc2-1720-11e8-994b-f68c6b8e6d09.png)

**Comment by tskisner** [comment]
Sorry for not being more clear.  I ran the toast_satellite_sim.py script with the central GHI wafer (band 21), for obs=0.01 and nside 2048.  Then I plotted the hit map with:
```
hp.gnomview(hits, rot=(-95.0, -0.3, 0.0), min=0.0, max=10.0, reso=1.0)
```
And here is the result:
![hits](https://user-images.githubusercontent.com/84221/36490558-5d8f4cb6-16dd-11e8-8d8f-38b479ac05a5.png)
So from this you can see that he detectors are aligned along the scan direction.  So I think we are good to go :-)

**Comment by zonca** [comment]
ok, good thanks
