### ISSUE TITLE
PICO Test calibration simulation, 2 days

### ISSUE THREAD

**Issue by zonca** [zonca/pico-simulations#5]
@ziotom78, I've run 2 days with the configuration in #4 for testing purposes.

See `/global/cscratch1/sd/zonca/pico/pico_calibration_sim_edison/`, this is in global scratch, so you can access it from any machine at NERSC.

I dumped the fits files and quickly checked them, I'll post some plots next.

**Comment by zonca** [comment]
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoYAAAFzCAYAAACjPchOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMS4xLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvAOZPmwAAIABJREFUeJzt3XuUHOWZ3/HfM6MLaC4Mi8AWLAZ7EXevjS+AAQsbwSKEvdgbbHNHKDmQ7HoT52SdOLvhEK03Odk9mxOfjR1iJyuNQFxswGa5EwwGBRAYsxgbYnMXBiyEDQzSCN3nzR9VPdPT05fq7up6q+r9fs6Bma5bP6OZ6f7N89ZbZc45AQAAAH2+CwAAAEA+EAwBAAAgiWAIAACAGMEQAAAAkgiGAAAAiBEMAQAAIIlgCABemNl6MzvVdx0AUI1gCKCQ4mC11czGzWyjma0ys8F43f1m9s+qth02s2+Y2a/i7Z+PH8+v2maZmf3czN41s9fN7EozG2ny/F81s6fMbLOZvWRmX+3tVwwAvUcwBFBkn3XODUr6iKSPS/oPtRuY2RxJ90o6StISScOSTpD0pqRj423+jaS/lvRVSXtJOl7SQZLuifevxyRdJGnv+LhfNrNzUvvKAMADgiGAwnPOvSbpTklH11l9kaT3Sfq8c+7/OecmnHNvOOe+7py7w8yGJa2Q9KfOubucczudc+slfVFROLygwXP+jXPuH51zu5xzz0j6B0knNqrRzC40s5fN7E0z+4uadcea2TozGzOzDWb2zUogNbNvmdl/rdn+VjP7Svz5vzOz1+LO5TNmtjjRPxoA1EEwBFB4ZnagpKWSnqiz+lRJdznnxhvsfoKkPSR9v3phvP2dkk5L8Pwm6ZOSnm6w/khJV0q6UNL+kvaR9LtVm+yW9K8lzZf0CUmLJf1xvG61pHPNrC8+1vx4/XVmdpikL0v6uHNuSNLpkta3qhcAGiEYAiiym81sTNKDkh6Q9J/rbLOPpA1NjjFf0m+dc7vqrNsQr2/lPyp6PV3VYP3Zkm5zzq11zm2XdLmkicpK59zjzrlH4u7jeknflnRyvO7Hkt5RFAYl6RxJ9zvnNioKlHMlHWlms51z651zLySoFwDqIhgCKLLPOedGnHMHOef+2Dm3tc42b0pa0OQYv5U038xm1Vm3IF7fkJl9WdFw9Zlx6Ktnf0mvVB4457bEdVWOcaiZ3RZPetmkKOBWB9LVmhrSvkDS1fFxnpf0FUXB9A0zu97M9m9WLwA0QzAEUHY/lHS6mQ00WL9O0nZJf1S9MN7+DEUTV+oys+WSviZpsXPu1SY1bJB0YNV+8xR1MiuulPRLSQudc8OS/lzR5JaKNZLOMrMPSTpC0s2VFc65a51zJyk6H9IpmkQDAB0hGAIou6sVdetuMrPDzazPzPYxsz83s6XOuXcUTT7572a2xMxmm9nBkm6Q9Gq8/wxmdr6izt5pzrkXW9Rwo6TPmNlJ8aSSv9T0198hSZskjZvZ4ZL+RfXOceh8LK7lpkpn1MwOM7NTzGyupG2StioaXgaAjhAMAZRaPLx7qqKO3D2KAtiPFQ3VPhpv8zeKunR/G69/VFGYXNxkePivFHX9HouvjThuZv+zQQ1PS/oTSdcq6h6+rSh0VvyZpPMkbZb0vyR9t85hVkv6oKYH1bmS/oui4e7XJe0Xfx0A0BFzzvmuAQDQgpktUjSkfLBzbqLV9gDQCTqGAJBzZjZb0r+S9L8JhQB6iWAIADlmZkdIGlM0Q/obnssBUHIMJQMAAEASHUMAAADECIYAAACQJNW70n9RMAYOAAAwk7XepL4iB0MAgVixYoXvEgrviiuu8F0CgAIo8uSTwhYOIELgyx8CJFAKHXcMCYYAeobgVz4ER6AQCIYAeo+gh3YRJAEvCIYA0kMARK8RGIGeIhgC6AwhEHlBWARSQzAEMB2BD2VFgARaIhgCoSMIIlQERWAGgiEQGoIgUB9BESAYAqVD8AN6g+CIABAMgaIjCAJ+EBRRQgRDoCgIgEAxEBhRYARDIK8IgkA5EBRRIARDIE8Ig0C5ERKRcwRDwAcCIIBqBEbkBMEQyAphEEAShER4RDAEeokwiE6Mjgxq2dh4R+skTVvfbHvkHyERGSMYAmkhBCKp6rBWL8wl2a+b51s2Nj7jWATI4iAsoocIhkA3CIPoRKtQ1ouQVu+YSZchvwiJSBnBEOgEgRDd6CYIJtm2nS5ku8+PfCIgIiUEQ6AVQiDa0WiottF2na5PWkfSdUmGt5N+bcgHwiI6QDAE6iEMohfqnetX+3nlsVS/45e0G9jqGO0MIRMEi4+QiIQIhoBEEET30gxW7Ya6bp+v0T5Jhrxru4iEyGIgKKKBjoNhX5pVAL6sWLGCUIiupR2Gmh2rdri3HZV9Ot23Xl2VZdUfR0cGO3oOZIfXPqSNjiEKixdDpKWTblnSENnuBJIk+3fSuexkf7qGxUQXEeqiYzgrzSqAXiIIolutgk47kzTSGG5OGkTTCmdJz3ms1NPLSTXondrXSoIi2kEwRO4RCJGWRkGmVejrJgBVglYnGu3XaLJLkloaPU+750ESCouj8hpKQEQSnGOI3OLcGWSpXghLeh5gp8EvSWjsJljWU3us6se16zqZaIP84jUVSdAxRG7wgoVeSdIRS2smcifn/rXqDHbbtWs1TN1NqEsy7Ix8YagZzdAxhHf8FYteSxKsupnpW62d/WtDWbvPnXT7ZttVr0vj0jgoHl6DUY1ZycgcL0DISqvQ08ls3U6uE9iqY9ntzOV2pH2dxlZ3XiE4FhedxELjOoYoBkIhslRviLNZ9yyNENNOGEo6A7jd5+/119iObjqi8IvX6zBxjiF6jhcXZK02nDUKh+1063oxQzdJJ7HdYzc6Z7DVPZTT6u4160aieKpfv+kghoGhZPQEYRB5kCT0dXKpliLKKhjWPmf183C7vfIgJOYe90pGPhAIUTaNwmURw02S8yN7/XwoFwJibnGOIfwjFCKvur0OYVnCTbN7JHeKIeKw8bpfPnQM0TFeEJBnjYYx621T2a7RjFo6X601+/fNeuY1/KKLmAt0DJEtQiHKpFkorKwPVTcdwZD/3ULG+0Ox0TFEW/iFR1FlNeECjfHvHR66h94w+QS9QxhE2dSboSvR4UoLARD1EBIzRTBE+giEKDPCS3qynu2MYiMgZoJgiHQQBgE00sktBIFmCIk9w+QTdI9QiBBweZXO1YbARhcGb4Z/f1TjfSd/6BiCX0wUBh2q/OF7grTQPUwVQ8loH4EQedcsdDCsmT/tfL+ARgiIqSAYoj2EQuQdQaK4Qrn/NHqHcNg1giGSIRCiqOgQFgffG6SFgNgxgiEaIwyiSAgVAOohJLaFWcmoj1CIIiEUAmiE97Ns0DEsMX6JAABlQ+cwEYaSESEMAgBCQUhsiKFkEAoBAGHhfS99dAxLgF8MAEDo6B5Ow1ByiAiEAABMR0CUxFByeAiFAADMxPtjd+gYFgw/8AjJ0Bcf1DfvOEMXj2/2XQqAAgq4e8hQcggIhQjJxB/9o/q+/xHfZQAouEDDIcGw7AiFAAB0JsBwSDAsKwIhQvHgojGdtHbEdxkASiyggEgwLBsCIULyxOKNOube9/guA0AgAgiIzEoGUCyr9h2Y/JxQCAD5QMcwR+gSAgCQrZJ2D+kYFh2hECFYtd9A640AIEO8/05Hx9AzfiBRdisPnqvl67f7LgMAWipR95DJJ0VEKESZXbd7WOf2b/JdBgC0pSThkGBYNIRCAADyqQThkGBYFARChGB0r0Ete2fcdxkA0JUCB0QmnxQBoRChaBYKP3DenRlWAnRndGTQdwnwKMT3bYIhgEy9eO0ZvksAEls2RucbYWEoucdC/GsDAIAyKtDQMkPJAAAA6A7BsIfoFgLSxs8857sEAEhFCO/rDCX3QAg/OEASD538tk58YG/fZQBdGx0Z5HxDTJPzYWWGkgH4d+3R01+L5u+xxVMlQLoIhQgFHcMU0SkEACAsOe0c0jH0jVCIkK0+dPbk5zccs1vrPvWWx2qA9HE9QzRStvd/OoYpKNsPBdCtrZ/7mfa8+fd9lwEAmclZ55COoS+EQmDKY6f8VpIIhQCCU5Y8QMewC2X5IQAAtMbMZCSRk84hHcOsEQqBSPX5hUCZEQqRRNHzAcGwA0X/pgNpuvjZnbr/k5t8lwH0HBNQkFSRcwJDyW0q8jcbANAdhpPRDo/DygwlZ4FQCMz06Kff9F0CkJlKKKR7iCSKmBvoGCZUxG8ukLar9xjShds2+y4D8IaOITrhoXPYcceQYJgAoRBojDdKAGgt43DIUHKvEAqBKat+b44k6cZjdk8uIxQiNAwjoxNFyRMEwyaK8k0EsnLJCzu0+tDZeu9QNJx8Tf+Q54qA7FQCIX8MoVNFyBUEQwCJrTmyTxM7+3TS2hHd/sKgzt/N+YYIR71ASPcQZcM5hnUUIdEDPqw8eK72X/C2lqyb57sUwDvOr0U3enzOIecYAui95eu3EwoRvE6GlNfdsKNX5QCpomNYg24hMN2aOUO6YAdDxgCQth52DekYpoFQCMx0wY7N3A8ZSMHll63xXQJyJo+5g45hLI/fHCAvVu6/pw446E3tWrOfzvw9zqkCJM4xRHp60DmkY9gNQiHQ3PB7xnX6unmEQgDogTzlEIIhgKbuPXFcZz/R77sMIDe4niHKLPhgmKeUDuTZbS9yMWtA6i4QPvrpN1OsBGWSlzwSdDDMyzcByKvRvQa1+KFB3f7CoD7zAWYmA40kvdD1cT/ah0koaCgPuSToYAighX23SxLnFgINtDusPDoyqK9/+4JelgR0JdhZyXlI5UDefe/DExq4aZhgCAAZSmGWcsezkoMMhoRCoLVbPr5Df/jYHN9lAECQugyHXK4GQHpWzR8gFAJAgIILhnQLgdbed9hGSdIdzyU7oR4AkC5feSWooWRCIZDc7S8Mcm4h0CPcNQVJdTikzDmGrRAKgWRG9xrU3r8wnbU/l6cBgDzoIBxyjiGA7t167HYddsyvNHtLYf9gBAB0YZbvAgDkx34D4zruR/tICxniAoAQBdExZBgZSGbjOLe9A3xYf8Z63yUgx7LMMaU/x5BQCLTn9ucHdeYhdAwBIG/aONeQcwwBpKNvl+8KgDBU31/57Eu+47ESYArBEIAk6cFFY7r76YEu/s4E0I7qy9XcuOpSLTzvdo/VAJFSDyUzjAwk88Tijdrl+vXmtw7WkiMYRgaAvEo4nMxQMoDOTbg+ffy++XJ0C4FMVQ8nA3lQ2o4h3UIgmSdPfV195vTBexb4LgUAkECCriF3PqlGKATad9+je+qU47b6LgMAkECLcMhQMoDOPP0Hv5Yk7Rzg5QDIGkPJyBveCYDA/fz1aAjZ8WoAAMEr3VAyw8hA+374+Dyd+tF3fZcBAGhDk+FkhpIBdG5iDtORAR9qh5L/7aWrPFUCREoVDOkWAu2pnF84MYtgCPhQfZFrSXp51w5PlaCIepF7ShUMAbRnggsXAt5Vdw2/u/Iyj5UABEMgePc8OY+7nQAeVXcNr9s17LESoETBkGFkoH0vje2j3bPpGgJ5sX3+hO8SUDBp55/SBEMA7fvDx+ZIRjAE8qL2nEMgawRDIEA/P23D5MQTFfeSVUApcJFr5AnBEAhQ9X2Rlxy5xWMlAIA8KUUw5PxCoD3X7+AEdyAvGD5Gt9LMQaUIhgDac86cTTrq/+zvuwwAYigZ+UIwBAJ04yY6hkBeLBsbnxYO112/TZJ0+WVrtO+XfuSrLASq8PdKZhgZAABg2r2TuVcygOSuGhjyXQKABtYuesd3CQjYLN8FAMjODePDcibNO+Zt6Yl+3+UAqGPR2r18l4CAFbpjyDAy0J4vDG7SFwc26Yh9N0qS7vwlJ70DeXXCRdfp8svW+C4DBZJGLqJjCASoMiPZJgp7jjFQag8uGpOuOlcP+y4EwSl0xxBAck+e+rokae39syeXGbkQyKWT1o5Mfk7XEFkiGAKB+NAP3ytJWvSpnZPLTj+Ku54AedHoeoZf//YFGVeCkBEMAQDIAe6AgjwgGAKBGN0r6kbc/fSA50oA1OLuJ8gLgiEQiIN//9eSpLFDuEwNkDd0C5EXBEMgEJ/6v8NafdgsfWnuJt+lAAByimAIBOTiZ3b5LgFAAwwnIw8IhgAA5ADDycgDgiEQmBuP2e27BAA1knQL6SgiCwRDIBB3PzWgGzYPa+4PRlpvDCBTy8bG6wa/gS88PG0boNe4JR4QiNOPji9mPRR9GB0Z5I0GyJF6v49bbjjBQyUIGR1DIBBzzn7UdwkAusBQMrJAMARKbvVh0cDAjhuPm7acbiFQLPzOIgsEQ6Dkai9R872tw54qAdCJyy9b47sEBIRgCARi4Xm3S5IGX5nwXAmAdnz92xf4LgEBIRgCgXju2jMlSUsPZTgKKCLOMUQWCIYAAOTMVYfN0qOfftN3GQgQwRAAgJy56JldenvbnpKkBxeNea4GISEYAiV33a5ossnNG6ILGD5yNUPJQBEsWTdPkvTsc/tLkg486nWf5SAQXOAaKLmtB+zSQafcpTO2LZB+8CEdfyHnKQFFsnzDu5Kk7bv7PVeCEBAMgZJbvvFdvXzdEs31XQiArix9ZE/fJSAADCUDAJAzZ1/yHUnS93/DdUeRLYIhAAA5c+OqSyVJY0fvarElkC6CIVByP/joTt8lAOjA9s8/ybs0MsePHFByn398tu8SALThuSW/kiRd+jvrtHzDu7r7qQHPFSEkBEMAAHLkg0OvSZJW//0/14tnvKyJWea5IoSEYAgE6Jr+Id8lAGhg2w2fmPz8gWcW6ozDx3XfSZs9VoSQFDoYXnHFFb5LAArpvY9yQjtQBPb2HEmSc3QN0VoauajQwRBAZxZ/bKvvEgAkMHjwO5KkxQ9xYXpkg2AIlNToCG8kQNGNb97DdwkITOGDIcPJAIAyuueELZr3JHc7QTJp5aHCB0MAAMrotIcHNPTKhO8yEBjulQyU0OjIoJaNjfsuA0CHVu03oL53+3Tx4cxGRrZK0TFkOBlo39r7uPA1kFeXvLFFF48TCpFMmjmoFMEQQGsPPDBn2uNFp3CrPCDP7n6aO54gewRDoITqDSOffPIOSdKDK57KuhwAHdh8YL8kcXFrZIpgCATmpCuO9l0CgATOHt4kiYtbI1vmnPNdQ6dmFL5ixQofdQAAAHjR4PzCjv+aoGMIAECOXNM3rBuP2e27DASKYAgAQI6cP7FJZz8RnV94/yc3ea4GoSlVMOSyNQCAMtm5u993CcixXuSeUgVDAPVx32SgWO5+ekD3nLBFpz3MJWuQrdIFQ7qGwEy1l6+56xcERSCvbnprWK8t3a0+K+zkUGSgV3mndMEQQGtLjuB2eUBezdrmtPzlbb7LQKAIhkCgbntpyHcJAOrY4+0JSdIE1y+EB6W6jmE1rmkITDc6Mlj3jigA8uOuXwxq92zpzEP4XUVjCYaRuY5hLc41BKarFwofuoOOBJAnziROLUQzvc43pQ2GAGaqnXRy4lLegYA8OePwcS1dOK57T6RjCD9KHQzpGgLTMekEyLfbX4j+eOP8QtSTRa4pdTAE0NojK8d8lwCgwkn3nbSZS9XAG4IhELjjl4/4LgGApDueHdSZh4xr5+5+LX6Ia43Cj9IHQ4aTgeYeXPGU7xIASFp6aHSqB91C1JNVnil9MJQIh0C12tvjnXTF0ZIYUgZ8u/OX0e8mwRC1sswxszJ7JgC5UO+yNT98fJ5OXe6hGACT3vyg6d5jxxlGhldBdAwBNHfqR9/1XQIQtDueHdQ/OfMhZiPDu2CCIcPJAIC8mphtevg3H9BpDw/4LgU5k3V+Ke0t8RrhVnkAgDy549lBbVnQpy8MbfJdCnKmi1DILfGSonMIRGonoQDwY+mh4xo4baPu/yTBEFN85ZXggiGAyLKxccIhkAN3PDeopY/sqd0TvCXDv+CGkisYUgYioyODdWcqA8jGmiP7tO9e4zp93TzfpSAnUugWMpTcLoaUgQihEPBr1pODXLsQk3znk2CDIQAAvt320pDOmb2Jy9QgN4IOhr5TOZAXnGsIZO/W9UNy8bsww8iQ8pFLgg6GUj6+CYBvDCcD2fvNCbv02YM26+5PcIF55CePBB8MAUyhcwhkZ/CF2ZK4NzLyJdhZybWYpQwAAHzoQbeQWcndyksLFwBQfisPnitJuvdETuMIXd7yBx3DGnQOAQC9dPXcIe31vDR47q91yoNDvsuBRz0MhXQM05K35A74dM1RXEIDSNuF2zfL9Yk7nQQur3mDn0oAM1QmoZz/dGFHFIDcunnDkM46YLNOe3jAdynADAwlN8GwMgAASFNGnUKGkgEAyLPvbhvWdbuGJUn3nLDFczVAfXQMW6BrCABIy60vD+mzB232XQY8yfC8QjqGvZLXk0MBAMXz2YM20y0MVFHyBB3DhOgcAgC6cfXcIV24nW5hiDyEQjqGvVaUpA80wu3ugGytXDBv2mNCYZiKlh/oGLaJziHKYnRkUMvGuOsCkIWbNwzpcwsIhqHxGAo77hgSDDtAOAQAAM147hQylJylorWFgUYYXgZ6Y9V+XLw6ZEXOCXQMu0DnEADQyk1vDWv4Mxu400kgchIKGUr2hXAIAGjk+h3DOmfOJt9lICM5CYUSQ8n+5OiHAOgaQ8tAugiF4ShLHiAYpqAsPwwIG7OUgfSsmT2kW9cPSZLuPZHfq7IrUw5gKDlFDCujLAiJAJBMTkMh5xjmCQERRUQYBLp3rRtW/3bpS3swhFx2OQ2EFZxjCKA71aGQcw2BzpxnmwiFKDQ6hj1E5xBFRgcRSO6a/iGdv5s7m4Qg553CCoaS84pwCABhuKZ/SHv/0mnpwnGtev9cXfLSdt8lIWUFCYVSF8FwVppVAAAQqvN3b5YWRp8TClFUdAwzRPcQAMplzewhXbCTIeQyK1CXsBqTTwD03ujIIBNTgCoX7Nys7/922HcZQGroGGaMriEAlMNVew7poq1Rt/CBB+bo5JN3eK4IaStot1Bi8knxEBBRBsxcBlBGBQ6EFQwlF00JfuiAGdc+ZJgZZbR6iJ/rkIT+/kzH0DM6hwAA5EOJQiFDyUVHQESZMMQMoEhKFAgrGEouuhL+UCJghEKUwap9BnyXgAzw/jsdHcOcooMIAEBvBBAG6RgCAACgO3QMc47OIQD4s2q/AV3yxhZJ0g82Dmn+k+/qk3+w23NV6FQAncIKJp+UHQERAIDOBBQIKxhKLrsAf6gBIDfW3jfbdwnoEO+f7SEYFgg/3ACQvbX3z9aiU3b6LgMd4H2zfQwlFxRDywDQW3c8O6ilh3LppSIiEHKOYZAIhwAATEcolEQwDBsBEQAQOgLhNARDEBABAOEhENbFrGTwywEACAvve+mjY1hidBABAGVDGEyEjiFm4pcHAFAmvK/1HsGw5PglAgCUAe9n2WAoOTAMLwMIxejIoJaNcR3CIiMMdoxZyWgPARFAyO76xaCWHEFozCsCYdc4xxDt4ZcOQKhuXT9EKMwx3p/8omMIuocACo0h43IgEKaKoWR0j4AIoIhGRwYliXBYUATCnmAoGd3jlxNAUVTCoEQgLDLed/KHjiEaooMIIO8YRi4ewmAmGEpG7xAQAeQVw8jFQSDMFMEQ2SAkAsgLuoX5Rxj0hmCIbBEQAQCNEAi9Y/IJssUvPQAfqiedIJ94fyg2OoZIDV1EAAgPQTCX6BjCP14cAPTa6MggXcMc4XW/fOgYoifoHgJIC5NM8odAmHtMPkF+ERIBoPgIg4VCMEQxEBIBoDgIg4XFOYYoBl5kAKAYeL0OEx1DeEcXEUAtzivMHkGwVBhKRvERENFMO0GB26QByREIS4lgiPIhKEJqv3NEpwlojiAYBIIhyouAWE5ZBzgCI0JHIAwKwRDlR0AsPsIZkD0CYZAIhggPQbEcGoXFXoRIzj3Mr5UH7Knlr231XUYpEAQhgiFCR0gsvlZBsJNQR4cSoSAMogbBEJAIiGVAmAOSIxCiAYIhUA9BsZjSDof1jkcAbYx/m/wiCCIhgiHQCiGx2BoNJVeHmCTbNFvWbHkZVb7W2o/IF8IgOkAwBDpBWAxHGkGwDMGp9mto9RjZIgQiJQRDoBsExOKr7RwmCTdJJryUYQi6iDWHhkCIlBEMgbQQEouv3cDXaCi11fKiKnr9ZUEYRA8RDIFeIizmW7NuYaN1RQlH7Zw3mfR4jc4nLMq/SRERApExgiGQFUJiftWGqHY7fo32b/WcnZ67WHm+2uesPE567HbDb739q2tAOgiD8IhgCPhASCyedoaF0+ygNerQ1ermPMlenGeJ9hAGkRMEQyBPCIzZazfgdDsUW/s4rTu39OpWgEmGjwmJyREAkXMEQyCvCIn+ZBF62r0GYCcdvlZDv80CX5L6kgxfgzCIQiEYAkVBUOy9emEoT8Gwop3A1mp9N+dDtloXKoIgCoxgCBQdgbG3srzkTKeTOZoFvSR3eGl2XAJhYwRAlBDBECgbgmL62u0gdjvjuNW5iPWGeyXN2K96WdJrNHI+YWMEQQSAYAiEhuCYXJJuYZJL2DQKbq3CXe2xGq1vp95O9gslDBL8AIIhEDyCYmvtTPzI8tp+jQJjq45lp+vLhiAIzEAwBDAdQTGZNIZX6w33Vj+uXlaRZEZxsxqbXby7cvyyBkOCINASwRBAZwiQkXbvktJqfaeXhwn5PEACH5AagiGA9BAWk0syrCs1v+RMO+vKEhYJgUBPEQwB9B6BcUqSWb/1JOlKlukcQQIg4AXBEED+ECTLh6AHFALBEEDxEBzzh+AHlALBEEB5ESC7R+ADgkIwBAAAgKQuguGsNKvIWMdfNAAAAGbq810AAAAA8oFgCAAAAEkEQwAAAMQIhgAAAJBEMAQAAECMYAgAAABJBEMAAADECIYAAACQRDAEAABAjGAIAAAASQRDAAAAxAiGAAAAkEQwBAAAQIxgCAAAAEkEQwAAAMQIhgAAAJBEMAQAAECMYAgAAABJ0izfBQA+zbcFboe2Rw/MZJUVNvm/KVb1uO76mmVWs7Lp41bHjbhG+7V8PsnVOXT9fSWZRds322ZGbU22a7RtguNWa+trqFme6Otp9tztPm/dda7xPi2P72Ysr7uLVT5M394P3cqjAAAFCElEQVTq1FL9824162r3qT5e9Y9pZXn1/tH6estrj+uarp957Kntbdrxp283fb+Zx6zdrnrb+sevWTft8+r6q7YzqeoVZcb2M9dFSx7/2fa7nXNLBHhCMETQdmi7jus7TdZnkvVNflSfRUGxL26qm0l9ffFHk1VtM2N95b9p66u2r7PemUX9+6r1rrJv1fLq7dzUO130eHJ5ZXtNO7aLl1XWTwYdk9RX2a/++mnLTNFzNVoXf4yee/qyaTVM1l5vuwbrNXXsevslOXZtbdM+r9l/arlrvH/1etXu66q20WRYql1v1dtOfo2VddM/SlPbm7n4R6N6nYt/JKbW98WfT66vWtanqceV9ZPrJte7yfV9leXxuurHk+snl09MPp7ad0L9k9tE6/sn18ePzalPlXUTk8futwn1yUUfbUL98TGq9++v2q+y/dS+0XNH20zE28T7xtv3a+o5+hXVUdm/P/66+lX9eXx8OfVZ/FFSv0n9sslhuX4z9cniZRY/7ouf29RvfepTn/oXPDdfgEcMJQMAAEASwRAAAAAxgiEAAAAkEQwBAAAQIxgCAABAEsEQAAAAMYIhAAAAJBEMAQAAECMYAgAAQBLBEAAAADFzbsYdRIFgmNlTkrb5rgMAYns45472XQTCxb2SEbptzrmP+S4CACTJzH7iuwaEjaFkAAAASCIYAgAAIEYwROi+47sAAKjCaxK8YvIJAAAAJNExBAAAQIxgCAAAAEkEQ5SIRf7OzJ43s5+Z2UcabPdRM/t5vN3fmZnFy3/HzO4xs+fij3vHyw83s3Vmtt3M/izLrwlAsZnZEjN7Jn69+Vqd9XPN7Lvx+kfN7OCqdf8+Xv6MmZ1etXylmb0RX4cVSBXBEGVyhqSF8X+XSrqywXZXxusr2y6Jl39N0r3OuYWS7o0fS9Jbkv6lpL/tTdkAysjM+iV9S9Fr05GSzjWzI2s2+6eS3nbOHSLpv0n663jfIyWdI+koRa9R/yM+niSNaup1C0gVwRBlcpakq1zkEUkjZrageoP48bBzbp2LZl5dJelzVfuvjj9fXVnunHvDOfeYpJ1ZfBEASuNYSc875150zu2QdL2i15lq1a87N0paHI9inCXpeufcdufcS5Kej48n59xaRX+wAqkjGKJMDpD0StXjV+Nltdu82mCb9zjnNkhS/HG/HtUJIAxJX5NekSTn3C5J70jaJ+G+QOoIhigTq7Os9npMSbYBgDR085rEaxW8IBii0MzsT8zsp2b2U0m/lnRg1erfjZdVezVeXm+bjZWh5/jjG72pGkAgXlWy16QDJcnMZknaS9EwcZJ9gdQRDFFozrlvOec+7Jz7sKSbJV0Uz04+XtI7laHhqu03SNpsZsfH5/FcJOkf4tW3SLo4/vziquUA0InHJC00s/eb2RxFk0luqdmm+nXnbEn3xec/3yLpnHjW8vsVTZT7cUZ1I2Dc+QSlEQe9byqarfeupEuccz+J1/00Do8ys48pmtW3p6Q7Jf2pc86Z2T6SvifpfZJ+JekLzrm3zOy9kn4iaVjShKRxSUc65zZl+fUBKB4zWyrpG5L6Ja10zv0nM/tLST9xzt1iZntIulrSMYo6hec4516M9/0LScsl7ZL0FefcnfHy6yR9StJ8SRslXeGc+/tsvzKUFcEQAAAAkhhKBgAAQIxgCAAAAEkEQwAAAMQIhgAAAJBEMAQAAECMYAgAAABJBEMAAADE/j9G7fB1LGFrFAAAAABJRU5ErkJggg==

**Comment by zonca** [comment]
![map](https://user-images.githubusercontent.com/383090/36098899-fbb29c2e-1000-11e8-9a23-a7b47ba8f782.png)
![tod_fg](https://user-images.githubusercontent.com/383090/36098932-1c223276-1001-11e8-8e49-0afceee2680c.png)
![tod_dipole](https://user-images.githubusercontent.com/383090/36098933-1c3cff48-1001-11e8-9fce-194b31b6753a.png)
![tod_total](https://user-images.githubusercontent.com/383090/36098935-1c53dc36-1001-11e8-9ed5-519070d27a0b.png)

**Comment by zonca** [comment]
@ziotom78 can you please check if the FITS files are fine?

**Comment by ziotom78** [comment]
@zonca, they seem ok, thanks!

**Comment by zonca** [comment]
ok I think we can prepare a larger run, what do you think is a reasonable amount of time it would make sense to simulate? I would like to stay between 2 and 6/7 months unless there are specific reason we need more. are you still of the idea of the full run to be 1 detector for 2 years?

**Comment by ziotom78** [comment]
The point is, the longer the acquisition, the better the calibration code can constrain the gain solution. Perhaps 1 year would still be fine, but if there is room I would go with 2 years.

**Comment by zonca** [comment]
do you think you can make a minimal calibration test with 6 months?

**Comment by ziotom78** [comment]
Sure! If it's just a matter of testing if the pipeline works and the file format is ok, even 15 days would be enough.

**Comment by zonca** [comment]
ok, let's do another test of 1 month and then we'll plan for a production
run of 2 years. at least let's propose this to Julian.

**Comment by zonca** [comment]
ok, I hope to run the 40 days simulation later this week, I'll open another issue with plots and location of the data.
